### ISSUE TITLE
A successful build should not be removed by default.

### ISSUE THREAD

**Issue by rwmacleod** [WindRiver-OpenSourceLabs/ci-scripts#1]
Currently, the default action after a successful build is to remove the build output image and tmp dir.

We need a way to connect to the image and runqemu, etc.

Konrad says that you can manually change the post-success arg to use rsync and tell it where to put the files but that could take some time and I hope we can use the result for interactive run-time testing, debugging, or even additional manual building.

**Comment by kscherer** [comment]
Rsync on successful build is now the default. If RSYNC_DEST_DIR is not defined the rsync script uses path that has the date in directory name.
